package rules.product1;

import com.example.hclai.drools_play_ground.model.UserData;
import com.example.hclai.drools_play_ground.model.RuleResult;

rule "femaleRule1"
    dialect "mvel"
    when
        $pdata: UserData( age >= 25 && age <= 65 && gender == "female" )
        $rr: RuleResult( result == "false" )
    then
        modify ( $rr ) { result = "true", approval = "supervisor1"}
end

rule "femaleRule2"
    dialect "mvel"
    when
        $pdata: UserData( age >= 50 && gender == "female" )
        $rr: RuleResult( result == "true" )
    then
        modify ( $rr ) { level = "high1", approval = "manager1"}
end